
name: Testing

defaults:
  run:
    working-directory: workshop/

on: [push, pull_request]

jobs:

  test:
    runs-on: macOS-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v2
    
    - name: cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-key: ${{ runner.os }}-gem-
    
    - name: install gems
      run: |
        bundle config path vendor/bundle
        bundle install --without=documentation --jobs 4

    # Runs a single command using the runners shell
    - name: fastlane-test
      run: bundle exec fastlane test
