
name: Testing

defaults:
  run:
    working-directory: workshop/

on: push

jobs:

  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: ruby versions
      run: |
        ruby --version
        gem --version
        bundler --version
    
    - name: cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('workshop/Gemfile.lock') }}
        restore-key: ${{ runner.os }}-gem-
    
    - name: install gems
      run: |
        bundle config path vendor/bundle
        bundle install --without=documentation

    # Runs a single command using the runners shell
    - name: fastlane-test
      run: bundle exec fastlane test
