# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
defaults:
  run:
    working-directory: workshop/

on: push

jobs:

  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: debug pwd
      run: pwd
      
    - name: ruby versions
      run: |
        ruby --version
        gem --version
        bundler --version
    
    - name: cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-key: ${{ runner.os }}-gem-
    
    - name: install gems
      run: |
        bundle config path vendor/bundle
        bundle install --without=documentation

    # Runs a single command using the runners shell
    - name: fastlane-test
      run: bundle exec fastlane test
